apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: store-simulator
  name: finn18-store-simulator-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: finn18
    server: https://kubernetes.default.svc
  project: finn18
  source:
    path: lab3-4/apps/store-simulator/overlays
    repoURL: https://github.com/jbcodeforce/eda-tech-academy.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
status:
  health: {}
  summary: {}
  sync:
    comparedTo:
      destination: {}
      source:
        repoURL: ""
    status: ""
