apiVersion: batch/v1
kind: Job
metadata:
  name: cp-ca-secret
  namespace: finn18
spec:
  template:
    metadata:
      name: cp-ca-secret
    spec:
      containers:
      - command:
        - bin/bash
        - -c
        - "if [ -z \"$(kubectl get secret es-demo-cluster-ca-cert -n finn18 | grep found)\" ]; \
          then kubectl get secret es-demo-cluster-ca-cert -n cp4i-eventstreams -o json \
          | jq -r '.metadata.namespace=\"finn18\"' \
          | jq  'del(.metadata.uid, .metadata.selfLink,.metadata.ownerReferences, .metadata.resourceVersion, .metadata.creationTimestamp)'  \
          | kubectl apply -n finn18 -f - ;\
          else echo already_created; fi"
        image: bitnami/kubectl
        name: copysecret
      restartPolicy: Never
      serviceAccountName: rt-inv-job-sa
